# fly.toml app configuration file generated for sleeping-dog-ai on 2026-06-15T21:35:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sleeping-dog-ai'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  NEXT_PUBLIC_SITE_URL = 'https://sleeping-dog-ai.fly.dev'
  NEXT_PUBLIC_SUPABASE_ANON_KEY = 'sb_publishable_p6UVlLp8E0sgZxPpf9wMSw_Cb2lYrl3'
  NEXT_PUBLIC_SUPABASE_URL = 'https://kvwabkhnhskzzibddslw.supabase.co'
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
